services:
  faveo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./faveo:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=faveo
      - DB_USERNAME=faveo
      - DB_PASSWORD=faveo_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=faveo
      - MYSQL_USER=faveo
      - MYSQL_PASSWORD=faveo_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - faveo_mysql:/var/lib/mysql

volumes:
  faveo_mysql: 