[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/bootstrap.sh"
healthcheckPath = "/public/health.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"] 