[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/bootstrap.sh"
healthcheckPath = "/health.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[envs.builder]
type = "nixpkgs"
nixpkgs = ["nodejs", "yarn"] 